% æ‡¿Îª≠Õº
close all;
figure(1);
plot(rec_dist(:,1), 'linewidth',2);
hold on;
plot(rec_dist(:,2), 'linewidth',2);
hold on;
plot(rec_dist(:,3), 'linewidth',2);
hold on;
plot(rec_dist(:,4)', 'linewidth',2);
hold on;
plot(rec_dist(:,5), 'linewidth',2);
grid on;
title('distance to goal');
xlabel('Iterations','fontsize',15);
ylabel('ditance to goal point [m]','fontsize',15);
% xlim([0 27]);
legend({'leader','agent1','agent2','agent3','agent4'},'fontsize',15);
% 
% % ÀŸ∂»ª≠Õº
% figure(2);
% plot(rec_speed(:,1), 'linewidth',2);
% hold on;
% plot(rec_speed(:,2), 'linewidth',2);
% hold on;
% plot(rec_speed(:,3), 'linewidth',2);
% hold on;
% plot(rec_speed(:,4)', 'linewidth',2);
% hold on;
% plot(rec_speed(:,5), 'linewidth',2);
% grid on;
% title('velocity of each agents');
% xlabel('Iterations','fontsize',15);
% ylabel('velocity','fontsize',15);
% xlim([0 27]);
legend({'leader','agent1','agent2','agent3','agent4'},'fontsize',15);
% ŒÛ≤Óæ‡¿Îª≠Õº
figure(3);
% plot(rec_dist(:,1), 'linewidth',2);
% hold on;
plot(rec_dist(:,2)-rec_dist(:,1), 'linewidth',2);
hold on;
plot(rec_dist(:,3)-rec_dist(:,1), 'linewidth',2);
hold on;
plot(rec_dist(:,4)-rec_dist(:,1), 'linewidth',2);
hold on;
plot(rec_dist(:,5)-rec_dist(:,1), 'linewidth',2);
grid on;
title('error of distance');
xlabel('Iterations','fontsize',15);
ylabel('error of distance','fontsize',15);
% ylim([-3 3]);
legend({'agent1','agent2','agent3','agent4'},'fontsize',15);
% ŒÛ≤ÓÀŸ∂»ª≠Õº
% figure(4);
% % plot(rec_dist(:,1), 'linewidth',2);
% % hold on;
% plot(rec_speed(:,2)-rec_speed(:,1), 'linewidth',2);
% hold on;
% plot(rec_speed(:,3)-rec_speed(:,1), 'linewidth',2);
% hold on;
% plot(rec_speed(:,4)-rec_speed(:,1), 'linewidth',2);
% hold on;
% plot(rec_speed(:,5)-rec_speed(:,1), 'linewidth',2);
% grid on;
% title('error of velocity');
% xlabel('Iterations','fontsize',15);
% ylabel('error of velocity','fontsize',15);
% % ylim([-3 3]);
% legend({'agent1','agent2','agent3','agent4'},'fontsize',15);
figure(5);
plot(costValue, 'linewidth',2);